#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 31 23:46:13 2018

@author: smrikva
"""

import pylab as plt
x = [i for i in range(100)]
#y = [i**2 for i in x]


plt.figure('quadratic')
plt.clf()
plt.plot(x,[i**2 for i in x], 'r', label='kvadratna funkcija od ' + str(min(x)) + ' do ' + str(max(x)))
plt.legend()